src/ECSL/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from ajax_select import urls as ajax_select_urls
from django.urls import include, path, re_path



urlpatterns = [
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^accounts/', include('django_registration.backends.activation.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
    re_path(r'', include('ecsl.urls')),
    re_path(r'^proposal/', include('proposal.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #+ views.becas


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/ecsl/urls.py
from django.urls import path

from ecsl import Profile
from ecsl import becas
from ecsl import charlas as speechviews
from ecsl import contact
from ecsl import payment
from ecsl import views
from ecsl.webservice import get_calendar_json

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('api/agenda.json', get_calendar_json, name="api_json"),
    path('agenda', speechviews.Charlas.as_view(), name="list_charlas"),
    path('edit-agenda', speechviews.EditCharlas.as_view(), name="edit_charlas"),
    path('miagenda', speechviews.MyAgenda.as_view(), name="mi_agenda"),

    path('charla/<int:pk>', speechviews.CharlaDetail.as_view(), name="detail_charla"),
    path('charla/registro/<int:pk>',
         speechviews.register_user_to_speech, name="registra_charla"),
    path('charla/desregistrar/<int:pk>',
         speechviews.desregistrar_charla, name="desregistrar_charla"),
    path('accounts/profile/', Profile.profile_view, name="profile"),
    path('register/profile/create',
         Profile.CreateProfile.as_view(), name='create_profile'),
    path('register/profile/update/<int:pk>', Profile.UpdateProfile.as_view(),
         name='edit_profile'),
    path('registro', payment.payment_view, name='payment'),
    path('registro/create', Profile.CreateRegister.as_view(), name='create_payment'),
    path('registro/update/<int:pk>', payment.PaymentUpdate.as_view(),
         name='edit_payment'),

    path('process-payment/<str:text>', payment.process_payment, name='process_payment'),
    path('payment-done/', payment.payment_done, name='payment_done'),
    path('payment-cancelled/', payment.payment_canceled, name='payment_cancelled'),
    path('sineventos/', views.noEvents, name='no-events'),
    path('becas/', becas.BecasCreate.as_view(), name="becas-create"),
    path('becas/detail/<int:pk>', becas.BecasDetail.as_view(), name="becas-detail"),
    path('contact/', contact.contactUs, name='contact-us'),
    path('contact/send/', contact.contact, name='contact'),
    path('participantes.js', views.get_participants, name="participantes"),
]

src/ecsl/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from datetime import date

from ecsl.managers import CurrentEventManager


class PaymentOption(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Nombre'))
    identification = models.CharField(
        max_length=30, verbose_name=_('Identificación'), null=True)
    tipo = models.CharField(max_length=255, verbose_name=_('Opción de envío'))
    email = models.EmailField()
    event = models.ForeignKey('EventECSL', on_delete=models.CASCADE, null=True, blank=False, verbose_name=_("Event"))
    objects = CurrentEventManager()

    def __str__(self):
        return "%s -- %s (%s)" % (self.tipo, self.name, self.identification)

    class Meta:
        verbose_name = "Opción de pago"
        verbose_name_plural = "Opciones de pago"


class Gustos(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Nombre'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Gusto"
        verbose_name_plural = "Gustos"


class Encuentros_Anteriores(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Nombre'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Encuentro anterior"
        verbose_name_plural = "Encuentros anteriores"


class Inscription(models.Model):
    STATUS = (
        (0, 'Creado usuario'),
        (1, 'Pre-registo'),
        (2, 'Confirmado'),
    )
    gender_choice = (
        ('Masculino', 'Masculino'),
        ('Femenino', 'Femenino'),
        ('Otro', 'Otro')
    )

    PAIS = (
        ('Panamá', 'Panamá'),
        ('Costa Rica', 'Costa Rica'),
        ('Nicaragua', 'Nicaragua'),
        ('El Salvador', 'El salvador'),
        ('Guatemala', 'Guatemala'),
        ('Honduras', 'Honduras'),
        ('Belize', 'Belize'),
        ('Otro', 'Otro'),

    )

    CAMISETA = (
        ('S', 'S'),
        ('XS', 'XS'),
        ('M', 'M'),
        ('XM', 'XM'),
        ('L', 'L'),
        ('XL', 'XL'),
        ('XXL', 'XXL')
    )

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name=_('Usuario'))
    status = models.SmallIntegerField(choices=STATUS, default=0)
    identification = models.CharField(
        max_length=50, verbose_name=_('Identificación en su país/pasaporte'), null=True,
        help_text='Requisito para hospedarse en hotel')
    direccion_en_su_pais = models.CharField(
        max_length=250, verbose_name=_('Dirección en su país'), null=True, blank=True,
        help_text='Requisito para hospedarse en hotel')
    born_date = models.DateField(
        verbose_name=_('Fecha de Nacimiento'), null=True)
    institution = models.CharField(
        max_length=250, null=True, blank=True, verbose_name=_('Institución'))
    gender = models.CharField(max_length=9, choices=gender_choice, verbose_name=_(
        'Género'), default='Masculino')
    nationality = models.CharField(
        max_length=12, choices=PAIS,  verbose_name=_('Nacionalidad'))
    other_nationality = models.CharField(max_length=12, null=True, blank=True,
                                         verbose_name=_('Si marcó otro indique el país de procedencia'))
    encuentros = models.ManyToManyField(Encuentros_Anteriores, blank=True,
                                        help_text="Use ctrl o command en mac para seleccionar más de uno",
                                        verbose_name=_("Encuentros anteriores en los que ha participado"))
    alimentary_restriction = models.TextField(null=True, blank=True,
                                              verbose_name=_('¿Tiene alguna necesidad específica de alimentación y hospedaje o alguna condición de salud especial?'))
    health_consideration = models.TextField(
        verbose_name=_('Condiciones de Salud'), null=True, blank=True)
    gustos_manias = models.ManyToManyField(Gustos,
                                           verbose_name="Por favor seleccione las opciones que correspondan a sus gustos, usos, costumbres, manías",
                                           help_text="Use ctrl o command en mac para seleccionar más de uno")
    observacion_gustos_manias = models.TextField(
        null=True, blank=True,
        verbose_name=_("Alguna otra observación sobre sus gustos, usos, costumbres y manías."))

    comentario_general = models.TextField(
        null=True, blank=True,
        verbose_name=_('Si tiene algún comentario y/o si quiere colaborar con la organización del ECSL por favor comente en este espacio.'))

    camiseta = models.CharField(max_length=10, choices=CAMISETA)
    hora_de_llegada = models.CharField(
        max_length=150, null=True, blank=True)
    hora_de_salida = models.CharField(
        max_length=150, null=True, blank=True)
    medio_de_transporte = models.CharField(
        max_length=150, null=True, blank=True)
    lugar_de_arribo = models.CharField(
        max_length=150, null=True, blank=True)
    observaciones_del_viaje = models.TextField(
        null=True, blank=True, help_text="Si viaja en avión agregue el número de vuelo.")
    aparecer_en_participantes = models.BooleanField(default=True)
    event = models.ForeignKey('EventECSL', on_delete=models.CASCADE, null=True, verbose_name=_("Event"))
    objects = CurrentEventManager()

    @property
    def name(self):
        return self.user.get_full_name()

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = "Inscripción"
        verbose_name_plural = "Inscripciones"


class Package(models.Model):
    name = models.CharField(max_length=40, default='',verbose_name=_("nombre"))
    description = models.CharField(max_length=100, default='', verbose_name=_("descripción"))
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name=_('precio'))
    event = models.ForeignKey('EventECSL', on_delete=models.CASCADE, null=True, blank=False, verbose_name=_("Event"))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Paquete"
        verbose_name_plural = "Paquetes"


class Payment(models.Model):

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name=_('Usuario'))
    option = models.ForeignKey(PaymentOption,
                               on_delete=models.CASCADE, verbose_name=_('Opción de pago'))
    codigo_de_referencia = models.CharField(max_length=40, verbose_name=_(
        'Id de transacción'), help_text="Identificación de transacción o código de referencia")
    invoice = models.FileField(upload_to="invoices/")
    confirmado = models.BooleanField(default=False)
    event = models.ForeignKey('EventECSL', on_delete=models.CASCADE, null=True, verbose_name=_("Event"))
    package = models.ForeignKey(Package, on_delete=models.CASCADE, null=True, verbose_name=_("Paquete"))
    objects = CurrentEventManager()

    @property
    def name(self):
        return self.user.get_full_name()

    def __str__(self):
        return "%s %s" % (self.user.get_full_name(), str(self.option))

    class Meta:
        verbose_name = "Pago"
        verbose_name_plural = "Pagos"


class Patrocinadores(models.Model):
    class Meta:
        verbose_name_plural = 'Patrocinador'
        verbose_name = 'Patrocinadores'

    TYPES = (
        ('gold', 'Oro'),
        ('Plate', 'Plata'),
        ('Bronce', 'Bronce'),
    )
    name = models.CharField(max_length=100, verbose_name=_('Nombre'))
    web = models.URLField(verbose_name=_('Web'))
    logo = models.ImageField(verbose_name=_('logo'), upload_to='logos/')
    patrocin = models.SmallIntegerField(choices=TYPES)
    event = models.ManyToManyField('EventECSL', verbose_name=_("Event"))


class Becas(models.Model):
    ESTADOS = (
        (0, 'Solicitada'),
        (1, 'Aprobada'),
        (2, 'Rechazada')

    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name=_('User'), null=True)
    razon = models.TextField(
        verbose_name="Dinos porqué deberíamos darte la beca")
    aportes_a_la_comunidad = models.TextField(
        verbose_name="¿Cúales son tus aportes a la comunidad ?")
    tiempo = models.CharField(
        max_length=250, verbose_name="Tiempo involucrado/a en el Software Libre, ej 2 años")
    observaciones = models.TextField(
        verbose_name="¿Alguna observación adicional?")
    estado = models.SmallIntegerField(choices=ESTADOS, default=0)
    event = models.ForeignKey('EventECSL', on_delete=models.CASCADE, null=True, blank=False, verbose_name=_("Event"))
    objects = CurrentEventManager()

    def __str__(self):
        return self.user.get_full_name() + " | " + str(self.event)

    class Meta:
        verbose_name = "Beca"
        verbose_name_plural = "Becas"


class EventECSL(models.Model):
    logo = models.ImageField(verbose_name=_("Logo"), null=True, upload_to='img/logos/',
                             blank=False)
    start_date = models.DateField(verbose_name=_("Start Date"), null=True)
    end_date = models.DateField(verbose_name=_("End Date"), null=True)
    location = models.CharField(max_length=50, null=True, verbose_name=_("Location"))
    description = models.TextField(verbose_name=_("Description"), null=True)
    current = models.BooleanField(default=False, verbose_name=_("Current"))
    organizer1 = models.CharField(max_length=25, null=True, verbose_name=_("First organizer"))
    organizer2 = models.CharField(max_length=25, null=True, verbose_name=_("Second organizer"))
    certificate_Header = models.ImageField(verbose_name=_("Certificate Header Image"), null=True, upload_to='img/logos/',
                             blank=True, help_text=_("Height 70px, Width 800px"))
    certificate_Footer = models.ImageField(verbose_name=_("Certificate Footer Image"), null=True, upload_to='img/logos/',

src/ecsl/forms.py
'''
Created on 2 jun. 2017

@author: luis
'''
from django import forms
from django.utils.translation import ugettext_lazy as _

from ecsl.models import Inscription, Payment, PaymentOption
from proposal.models import SpeechSchedule


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(label=_("First name"))
    last_name = forms.CharField(label=_("Last name"))

    field_order = [
        'first_name', 'last_name',
        'identification',
        'direccion_en_su_pais',
        'nationality', 'other_nationality',
        'gender', 'camiseta',
        'born_date', 'institution',
        'encuentros',
        'alimentary_restriction', 'health_consideration',
        'gustos_manias', 'observacion_gustos_manias',
        'comentario_general',
        'hora_de_llegada', 'hora_de_salida', 'medio_de_transporte',
        'lugar_de_arribo', 'observaciones_del_viaje', 'aparecer_en_participantes'
    ]

    def __init__(self, *args, **kwargs):
        self.user = None
        if 'instance' in kwargs and kwargs['instance']:
            self.user = kwargs['instance'].user

        if 'request' in kwargs:
            request = kwargs.pop('request')
            self.user = request.user
        if self.user:
            kwargs['initial']['first_name'] = self.user.first_name
            kwargs['initial']['last_name'] = self.user.last_name

        super(ProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        dev = super(ProfileForm, self).save(commit=commit)
        user = None
        if self.instance:
            user = self.instance.user
        elif self.user:
            user = self.user
        if user:
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()
        return dev

    class Meta:
        model = Inscription
        fields = '__all__'
        exclude = ['user', 'status', 'event']


class PaymentForm(forms.ModelForm):
    option = forms.ModelChoiceField(widget=forms.RadioSelect,
                                    queryset=PaymentOption.objects.all().exclude(name="Beca").exclude(name="Paypal"),
                                    label="Opción de pago",
                                    empty_label=None)

    class Meta:
        model = Payment
        fields = '__all__'
        exclude = ['user', 'confirmado', 'event']


class ContactForm(forms.Form):
    Name = forms.CharField(
        label=False,
        min_length=2,
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Name'),
                'class': 'form-control',
            }
        )
    )

    Email = forms.CharField(
        label=False,
        min_length=6,
        max_length=50,
        widget=forms.EmailInput(
            attrs={
                'placeholder': _('Email'),
                'class': 'form-control',
            }
        )
    )

    Subject = forms.CharField(
        label=False,
        min_length=2,
        max_length=150,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Subject'),
                'class': 'form-control',
            }
        )
    )

    Message = forms.CharField(
        label=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': _('Message'),
                'class': 'form-control',
            }
        )
    )


class scheduleForm(forms.ModelForm):
    is_speech = forms.BooleanField(required=False)
    text = forms.CharField(max_length=250)
    color = forms.CharField(max_length=10)

    class Meta:
        model = SpeechSchedule
        fields = '__all__'

src/ecsl/templates/ecsl/becas_detail.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <h1> {% trans 'Scholarship Detail' %} </h1>
        </div>
    </div>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <strong> {% trans 'State' %} </strong>
            </div>
            <div class="col-md-9 ">
                {{ object.get_estado_display }}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <strong> {% trans 'Reasons for applying to the scholarship' %} </strong>
            </div>
            <div class="col-md-9 ">
                {{ object.razon}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <strong> {% trans 'Community Contributions' %} </strong>
            </div>
            <div class="col-md-9">
                {{ object.aportes_a_la_comunidad}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <strong> {% trans 'Time involved in Free Software' %} </strong>
            </div>
            <div class="col-md-9">
                {{ object.tiempo}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-3">
                <strong> {% trans 'Additional observations' %} </strong>
            </div>
            <div class="col-md-9">
                {{ object.observaciones}}
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
{% endblock content %}

src/ecsl/templates/ecsl/becas_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div>
                <h1> {% trans 'Create Scholarship' %} </h1>
            </div>

            <div class="row">
                <form method="post">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

src/ecsl/templates/ecsl/certificaciones.html
{% load static %}
{% load i18n %}

<html>
<style type="text/css">
@page {
    size: letter portrait;
	@frame header_frame {           /* Static frame */
	    -pdf-frame-content: header_content;
	     width: 21.5cm;  height: 2cm;

	}
	@frame content_frame {          /* Content Frame */
	    left: 1cm; width: 19cm; top: 3cm; height: 22.2cm;
	    
	}
	@frame footer_frame {           /* Static frame */
	    -pdf-frame-content: footer_content;
	     width: 21.5cm; top: 26cm; height: 2cm;
	}
}

body{
font-size: 2em;
}
</style>
<body>
<div id="header_content" >
    {% if event.certificate_Header %}
        <img  src="{{ event.certificate_Header.url }}" alt="logo" />
    {% endif %}
</div>


<div id="content" >
<br>
{% for insciption in object_list %}
<div >
<center>
<p>

Software Libre Centroamérica (SL-CA) y el comité organizador del Encuentro Centroamericano de Software Libre (ECSL
    {{ event.start_date.year }}) otorgan el presente <strong>certificado de participación</strong> a:
</p>
<h1 style="color:#709f2c; font-size: 3em">{{ insciption.user.get_full_name }}</h1>

<p>
Por su destacado aporte a la comunidad centroamericana durante el ECSL {{ event.start_date.year }}.</p>
<br>
<p>
Dado en la ciudad de {{ event.location }}, el dia {{ event.start_date }}
</p>

</center>
</div>
<div style="font-size: 1em;">
<br><br>
_______________________ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_______________________  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ event.organizer1}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ event.organizer2}}   <br>
Comité organizador del ECSL {{ event.start_date.year }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comité organizador del ECSL {{ event.start_date.year }} <br>

</div>
{% if not foorloop.last%}
<pdf:nextpage />
{% endif %}
{% endfor %}
</div>
<div id="footer_content">
    {% if event.certificate_Footer %}
        <img  src="{{ event.certificate_Footer.url }}" alt="logo" />
    {% endif %}
</div>
</body>
</html>

src/ecsl/templates/ecsl/inscription_form.html
{% extends 'base.html' %}
{% load bootstrap static %}
{% load i18n %}

{% block content %}

<div class="row">
  <div class="col-md-6 col-md-offset-3">  	
<div>
  <h1>{% trans 'My profile' %}</h1>
</div>

<div class="row">
  <form method="post" action="">
    {% csrf_token %}
    {{ form|bootstrap  }}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
    </div>
  </form>
</div>

  </div>
</div>
{% endblock %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script>
$("#id_hora_de_llegada").closest('.form-group').before(
'<div class="page-header"><h2 class="text-center text-success">Itinerario de viaje<br><small>No indispensable para costarricenses </small></h2></div>');

$('#id_born_date').bootstrap_datepicker({ format: "dd/mm/yyyy"});
$("#id_nationality").on('change', function(){
	console.log($(this).val());
	if($(this).val() == 'Otro'){
		$("#id_other_nationality").closest('.form-group').show();
	}else{
		$("#id_other_nationality").closest('.form-group').hide();
	}
	
});

if($("#id_nationality").val() == 'Otro'){
	$("#id_other_nationality").closest('.form-group').show();
}else{
	$("#id_other_nationality").closest('.form-group').hide();
}
</script>
{% endblock %}

src/ecsl/templates/ecsl/payment_cancelled.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <p>{% trans "The inscription payment was cancelled, please check your balance or check that you are not already enrolled." %}</p>

{% endblock %}

src/ecsl/templates/ecsl/payment_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <p>{% trans "The registration payment is done, please return to the index." %}</p>

{% endblock %}

src/ecsl/templates/ecsl/payment_form.html
{% extends 'base.html' %}
{% load bootstrap static %}
{% load i18n %}

{% block content %}
<div class="row">

<div class="col-md-6 ">

<div class="well">
<h1>Distribución de personas aceptando dinero</h1>
<p>
<div class="alert alert-danger"> * El encuentro es muy pronto y ya no estamos recibiendo pagos por envío de dinero, 
si usted no puede hacer el pago bancario, por favor comuniquese con la coordinación, para gestionar la forma de pago</div>

</div>
<br><br>
<div class="well">
<h1>Información bancaria detallada</h1>
<p><b>Nombre del banco:</b> Banco Nacional de Costa Rica</p>
<p>Dialogía de Información y Comunicación S.C.<br>

    <b>Cuenta IBAN (Internacional):</b> CR38015109620020034632<br>
    <b>Cuenta Banco Nacional (CR):</b> 200-02-096-003463-0<br>
    <b>Cuenta Cliente (CR):</b> 15109620020034632<br>
    <b>Cédula jurídica:</b> 3-106-562299<br>
</p>
<p><b>Cuenta a nombre de:</b> Dialogía de Información y Comunicación SC</p>
<p><b>Dirección postal de la oficina principal del banco:</b> Avenidas 1 y 3, calle 3. San José, Costa Rica.</p>
<p><b>SWIFT bic:</b> BNCRCRSJ</p>
<p>Datos del banco corresponsal o intermediario en USA</p>
<p><b>Nombre del Banco corresponsal:</b> Citibank</p>
<p><b>Dirección del banco corresponsal:</b> New York 339 Park Avenue New York, NY 10022. USA</p>
<p><b>Código ABA del corresponsal:</b> CITIUS33</p>
</div>


</div>


  <div class="col-md-6">  	<div>
  <h1>{% trans "Inscription Payment"%}</h1>
</div>

<div class="row">
    <label>Paypal</label>
<input type="checkbox" id="paypal"></input>



  <form method="post" action="" enctype="multipart/form-data">

      </br>
    {% csrf_token %}
    {{ form.package|bootstrap  }}
    <div id="form-A">
    {{ form.option|bootstrap  }}
    {{ form.codigo_de_referencia|bootstrap  }}
    {{ form.invoice|bootstrap  }}

    <div class="form-group">
      <button type="submit" class="btn btn-primary">Registrarme</button>
    </div>
  </form>
</div>

<div id="form-B" style="display: none;">
    </br>
    <label>{% trans "Register with Paypal." %}</label>
    </br>
    <input type="button" class="btn btn-primary" onclick="selectedSubjectName()"  id='usePaypal' value="Paypal" />
</div>


</div>
</div>
</div>


{% endblock %}

{% block js %}
    <script>
        $('#paypal').change(function(){
                    if ($(this).is(":checked")) {
                        $("#form-A").hide();
                        $("#form-B").show();
                    } else {
                        $("#form-A").show();
                        $("#form-B").hide();
                    }
        });
    </script>
<script>
    function selectedSubjectName() {
      var subjectIdNode = document.getElementById('id_package');
      var value = subjectIdNode.options[subjectIdNode.selectedIndex].text;
      console.log("The selected value=" + value);
      url = "{% url "process_payment"  999 %}".replace(999,value)
      document.location.href= url
   }

</script>
{% endblock %}

src/ecsl/templates/ecsl/process_payment.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Make Payment{% endblock %}

{% block content %}
    <h2>{{ price }}</h2>
    <H3>{{ price.description }}</H3>
    </br>
    <h1>{% trans "Pay with paypal." %}</h1>
    {{ form.render }}
{% endblock %}

src/ecsl/templates/ecsl/ud_esta_aqui.html
{% load static %}
<html>
<style type="text/css">
@page {
    size: letter portrait;
	@frame header_frame {           /* Static frame */
	    -pdf-frame-content: header_content;
	     width: 21.5cm;  height: 2cm;

	}
	@frame content_frame {          /* Content Frame */
	    left: 1cm; width: 19cm; top: 3cm; height: 22.2cm;
	    
	}
	@frame footer_frame {           /* Static frame */
	    -pdf-frame-content: footer_content;
	     width: 21.5cm; top: 26cm; height: 2cm;
	}
}
</style>
<body>
<div id="header_content">
	<img  src="{% include 'ecsl/pdf_header.html' %}" alt="logo" />
</div>
<div id="content" > 

{% for room in object_list %}
<div >
<center>
<h1 style="color:#709f2c; font-size: 3em"> {{room.name}} </h1> <br><br>
<img style="text-align: center;" src="{{room.map.url}}"  />

</center>
</div>

{% if not foorloop.last%}
<pdf:nextpage />
{% endif %}
{% endfor %}
</div>
<div id="footer_content"> 
<img  src="{% include 'ecsl/pdf_footer.html' %}" alt="logo" />
</div>
</body>
</html>