src/ECSL/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from ajax_select import urls as ajax_select_urls
from django.urls import include, path, re_path



urlpatterns = [
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^accounts/', include('django_registration.backends.activation.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
    re_path(r'', include('ecsl.urls')),
    re_path(r'^proposal/', include('proposal.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #+ views.becas


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/proposal/urls.py
# encoding: utf-8

'''
Free as freedom will be 27/10/2016

@author: luisza
'''

from __future__ import unicode_literals
from proposal import views, types, topics, special_activities, rooms
from django.urls import path

app_name = 'proposal'
urlpatterns = [
    path('', views.SpeechListView.as_view(), name='speech-list'),
    path('create/', views.createUpdateview, name='create'),
    path('<int:speech_id>/update/', views.createUpdateview, name='update'),
    path('<int:speech_id>/delete/', views.deleteView, name='delete'),
    path('createTopic/', topics.CreateTopic.as_view(), name='create-topic'),
    path('createType/', types.CreateType.as_view(), name='create-type'),
    path('createRoom/', rooms.CreateRoom.as_view(), name='create-room'),
    path('filterSpeeches/', views.get_all_speeches, name='filter-speeches'),
    path('createSpecial/', special_activities.CreateSpecialActivity.as_view(), name='create-special'),
]

src/proposal/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ecsl.managers import CurrentEventManager
from ecsl.models import EventECSL


class Topic(models.Model):
    name = models.CharField(max_length=150, verbose_name=_("Name"))
    color = models.CharField(max_length=10, default="#fff")
    event = models.ForeignKey(EventECSL, on_delete=models.CASCADE, null=True, blank=False, verbose_name=_("Event"))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Temática"
        verbose_name_plural = "Temáticas"


class SpeechType(models.Model):
    name = models.CharField(max_length=150, verbose_name=_("Name"))
    time = models.IntegerField(default=10, verbose_name=_("Duration (in minutes)"))
    event = models.ForeignKey(EventECSL, null=True, default=None, on_delete=models.CASCADE, verbose_name=_("Event"))
    is_special = models.BooleanField(default=False, verbose_name=_('Is Special Activity'))
    objects = CurrentEventManager()

    def __str__(self):
        return _("%s (%d minutes)") % (self.name, self.time)

    class Meta:
        verbose_name = "Tipo de actividad"
        verbose_name_plural = "Tipos de actividad"


class Speech(models.Model):
    class SKILL_LEVEL:
        EVERYONE = 1
        NOVICE = 2
        INTERMEDIATE = 3
        ADVANCED = 4

        choices = [
            (EVERYONE, _('everyone')),
            (NOVICE, _('novice')),
            (INTERMEDIATE, _('intermediate')),
            (ADVANCED, _('advanced')),
        ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Usuario'))
    speaker_information = models.TextField(
        verbose_name=_("Speaker_information"))
    title = models.TextField(verbose_name=_("Speech Title"))
    description = models.TextField(verbose_name=_("Description"))
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              verbose_name=_("Topic"))
    audience = models.TextField(verbose_name=_("Audience"))
    skill_level = models.PositiveIntegerField(
        choices=SKILL_LEVEL.choices, default=SKILL_LEVEL.EVERYONE,
        verbose_name=_("Skill level required"))
    notes = models.TextField(blank=True,
                             verbose_name=_("Notes for audience"))
    speech_type = models.ForeignKey(SpeechType, on_delete=models.CASCADE, verbose_name=_("Speech Type"))

    presentacion = models.FileField(upload_to='presentaciones/',
                                    verbose_name=_("Presentation"),
                                    null=True, blank=True)
    event = models.ForeignKey(EventECSL, null=True, blank=False, on_delete=models.CASCADE, verbose_name=_("Event"))
    is_scheduled = models.BooleanField(default=False, verbose_name=_('is Scheduled'))

    objects = CurrentEventManager()

    @property
    def speaker_name(self):
        return self.user.get_full_name()

    @property
    def speaker_registered(self):
        dev = False
        try:
            dev = self.user.payment.confirmado
        except:
            pass
        return dev

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('pk',)
        # permissions = (
        #     ("view_speech", "Can see available Speech"),
        # )

        verbose_name = "Actividad"
        verbose_name_plural = "Actividades"


class Room(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Nombre'))
    spaces = models.SmallIntegerField(default=30, verbose_name=_('Spaces'))
    map = models.ImageField(upload_to="mapa", null=True, blank=True, verbose_name=_('Map'))
    event = models.ForeignKey(EventECSL, on_delete=models.CASCADE, verbose_name=_("Event"), null=True, default=None)
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Sala"
        verbose_name_plural = "Salas"


class Register_Speech(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    speech = models.ForeignKey('SpeechSchedule', on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.user.get_full_name(), self.speech.speech.title)

    class Meta:
        verbose_name = "Registro en actividad"
        verbose_name_plural = "Registros en actividades"


class SpeechSchedule(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    speech = models.ForeignKey(Speech, on_delete=models.CASCADE, null=True, blank=True)
    special = models.ForeignKey('SpecialActivity', on_delete=models.CASCADE, null=True, blank=True)
    room = models.ForeignKey('Room', on_delete=models.CASCADE, null=True, default=None)

    def __str__(self):
        return "(%s %s) %s" % (self.start_time.strftime("%Y-%m-%d %H:%M"),
                                     self.end_time.strftime("%Y-%m-%d %H:%M"),
                                     self.room.name)

    @property
    def title(self):
        return self.room.name + " "+str(self.start_time)+" "+str(self.end_time)

    def registros(self):
        regs = Register_Speech.objects.filter(speech=self).count()
        total = self.room.spaces - regs

        dev = "Lleno"
        if total > 0:
            dev = "Hay %d espacios" % (total,)

        return dev

    class Meta:
        verbose_name = "Horario de actividad"
        verbose_name_plural = "Horarios de actividades"


class SpecialActivity(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    type = models.ForeignKey(SpeechType, null=True, on_delete=models.CASCADE, verbose_name=_("Type"))
    message = models.TextField(null=True, blank=True, verbose_name=_("Message"))
    room = models.ForeignKey('Room', null=True, default=None, blank=True, on_delete=models.CASCADE, verbose_name=_("Room"))
    event = models.ForeignKey(EventECSL, default="", on_delete=models.CASCADE, verbose_name=_("Event"))
    is_scheduled = models.BooleanField(default=False, verbose_name=_('is Scheduled'))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actividad Especial"
        verbose_name_plural = "Actividades Especiales"


class BlockSchedule(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    is_speech = models.BooleanField()
    text = models.TextField(null=True, blank=True)
    color = models.CharField(max_length=10)
    room = models.ForeignKey('Room', null=True, default=None, on_delete=models.CASCADE, verbose_name=_("Room"))

    def __str__(self):
        return "%s %s" % (self.start_time.strftime("%Y-%m-%d %H:%M"),
                          self.end_time.strftime("%Y-%m-%d %H:%M"),)

    def get_speech(self, user=None):
        query = SpeechSchedule.objects.filter(
            start_time=self.start_time,
        )
        if user:
            query = query.filter(register_speech__user=user)

        return query.order_by('start_time')

    class Meta:
        verbose_name = "Bloque de horario"
        verbose_name_plural = "Bloques de horarios"

src/proposal/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Speech, Topic, SpeechType, SpecialActivity, Room


class SpeechForm(forms.ModelForm):
    speech_type = forms.ModelChoiceField(queryset=SpeechType.objects.filter(is_special=False), label=_("Type"))

    class Meta:
        model = Speech
        exclude = ('user', 'event', 'is_scheduled',)


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'


class TypeForm(forms.ModelForm):
    class Meta:
        model = SpeechType
        fields = '__all__'


class SpecialActivityForm(forms.ModelForm):
    type = forms.ModelChoiceField(queryset=SpeechType.objects.filter(is_special=True), label=_("Type"))

    class Meta:
        model = SpecialActivity
        exclude = ('event', 'is_scheduled', 'room')


class RoomsCreateForm(forms.ModelForm):
    class Meta:
        model = Room
        exclude = ('event',)

src/proposal/views.py
from django.contrib import messages
from django.core import serializers
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.views import generic

from ecsl.models import EventECSL
from proposal.models import Speech
from .forms import SpeechForm
from .models import SpeechType


# Create your views here.

class SpeechListView(generic.ListView):
    template_name = 'proposal/speech_list.html'
    context_object_name = 'speech_list'
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        event = EventECSL.objects.filter(current=True).first()
        context = generic.ListView.get_context_data(self, **kwargs)
        if event.checking_period:
            context['period'] = event.checking_period
        return context

    def dispatch(self, request, *args, **kwargs):
        proposal = None
        event = EventECSL.objects.filter(current=True).first()
        if not self.request.user.is_authenticated and event:
            messages.warning(
                self.request, _("We are sorry! You have to be registered as a system user to be able to send"
                                "a proposal speech"))
            return redirect(reverse_lazy('index'))
        elif not event:
            return redirect(reverse('index'))
        elif request.user.is_authenticated:
            try:
                proposal = request.user.speech_set.count()
                if proposal > 0:
                    proposal = True
                else:
                    proposal = None
            except Exception as e:
                pass
        if not event.checking_period and not proposal:
            messages.warning(
                self.request, _("We are sorry! The proposal speech period is not active"
                                ))
            return redirect(reverse('index'))
        return super(SpeechListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        event = EventECSL.objects.filter(current=True).first()
        if event:
            return Speech.objects.filter(user=self.request.user, event=event)


def get_color_speech(request, result):
    colors = None
    if result:
        colors = []
        for speech in result:
            colors.append(speech.topic.color)
    return colors


def get_times_speech(request, result):
    times = None
    if result:
        times = []
        for speech in result:
            times.append(speech.speech_type.time)
    return times


def get_all_speeches(request):
    if request.method == 'POST':
        result = []
        colors = []
        event = EventECSL.objects.filter(current=True).first()
        if event and 'topic' in request.POST and 'type' in request.POST:
            if request.POST['topic'] == 'None' and request.POST['type'] == 'None':
                result_query = Speech.objects.filter(event=event, is_scheduled=False)
                result = serializers.serialize('json', result_query)

            elif request.POST['topic'] == 'None' and request.POST['type'] != 'None':
                result_query = Speech.objects.filter(event=event, speech_type=request.POST['type'],
                                                     is_scheduled=False)
                result = serializers.serialize('json', result_query)

            elif request.POST['type'] == 'None' and request.POST['topic'] != 'None':
                result_query = Speech.objects.filter(event=event, topic=request.POST['topic'],
                                                     is_scheduled=False)
                result = serializers.serialize('json', result_query)
            else:
                result_query = Speech.objects.filter(event=event, speech_type=request.POST['type'],
                                                     is_scheduled=False, topic=request.POST['topic'])
                result = serializers.serialize('json', result_query)

            times = get_times_speech(request, result_query)
            colors = get_color_speech(request, result_query)
            types = SpeechType.objects.filter(is_special=False)
            types = serializers.serialize('json', types)
        return JsonResponse(data={'result': result, 'color': colors, 'times': times, 'types': types, })


def deleteView(request, speech_id):
    if request.method == 'POST':
        speech = Speech.objects.get(pk=speech_id)
        speech.delete()
    return HttpResponseRedirect(reverse('proposal:speech-list'))


def createUpdateview(request, speech_id=None):
    context = {}
    speech_form = SpeechForm()
    event = EventECSL.objects.get(current=True)
    proposal = None
    if not request.user.is_authenticated and event:
        messages.warning(
            request, _("We are sorry! You have to be registered as a system user to be able to send"
                       "a proposal speech"))
        return redirect(reverse_lazy('index'))
    elif not event:
        return redirect(reverse('index'))
    elif request.user.is_authenticated:
        if speech_id != None:
            if Speech.objects.filter(id=speech_id).first().user != request.user:
                return redirect(reverse_lazy('index'))
        try:
            proposal = request.user.speech_set.count()
            if proposal > 0:
                proposal = True
            else:
                proposal = None
        except Exception as e:
            pass
    if not event.checking_period and not proposal:
        messages.warning(
            request, _("We are sorry! The proposal speech period is not active"
                       ))
        return redirect(reverse('index'))
    if request.method == 'POST' and not speech_id:
        speech_form = SpeechForm(request.POST)
        if speech_form.is_valid():
            form = speech_form.save(commit=False)
            form.user = request.user
            form.event = event
            form.save()
    elif request.method == 'POST' and speech_id:
        speech = Speech.objects.filter(pk=speech_id).first()
        speech_form = SpeechForm(request.POST, instance=speech)
        if speech_form.is_valid():
            form = speech_form.save(commit=False)
            form.event = event
            form.save()
    elif speech_id and request.method == 'GET':
        speech = Speech.objects.filter(pk=speech_id).first()
        speech_form = SpeechForm(instance=speech)

    context['speech_form'] = speech_form

    if request.method == 'POST':
        return HttpResponseRedirect(reverse('proposal:speech-list'))
    else:
        return render(request, "proposal/speech_form.html", context)

src/proposal/templates/proposal/edit_agenda.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap %}
{% load registro_charla %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
    </div>
</div>


{% endblock %}

src/proposal/templates/proposal/mi_agenda.html
{% extends 'base.html' %}
{% load i18n %}
{% load registro_charla %}

{% block content %}
<style>
.theader{
	text-decoration: blond;
	background-color: #98978b;
	padding: 10px 2px;
	text-align: center;
	color: #fff;
	margin-bottom: 5px;
}

.speech_row {
	
	padding: 10px 5px;
	text-align: left;
}

.text_row  {
	padding: 10px 0px;
	color: #fff;
	font-weight: bold;
}
</style>
<div class="pull-right">
<a class="btn btn-danger" href="{% url 'list_charlas' %}?dia=1"> Ver todos los eventos </a>
</div>

<br><br>
<h2> Temáticas </h2>


<div class="row">
 <div class="col-md-1"></div>
{% for tipo in tipos %}
 <div class="col-md-2" style="color: {{tipo.color}}"> {{tipo.name }} </div>
{% endfor %}
</div>


<hr>

<ul class="nav nav-tabs">
  {% for d in dayList %}
        <li role="presentation" class="{% if dia ==  forloop.counter  %} active {% endif %}">
        <a href="{% url 'mi_agenda' %}?dia={{ forloop.counter }}">{{ d }}</a></li>
  {% endfor %}


</ul>
<br ><br>


<div class="row theader">
  <div class="col-md-2">Horario</div>
  <div class="col-md-5">Título</div>
   <div class="col-md-2">Expositor/a responsable</div>
  <div class="col-md-1">Salón</div>
  <div class="col-md-2">Registro</div>
</div>

	{% for obj in object_list %}
		
		<div id="block_{{obj.pk}}" class="row {% if obj.is_speech %}speech_row{% else %} text_row {%endif%}" style="background-color:{{obj.color}}">
		{% if obj.is_speech %}
		  {% get_speech obj as sobj %}
		  {% for speech in sobj %}
		  <div class="row">
		  <div class="col-md-2">{{ speech.start_time | date:"P" }} a {{ speech.end_time | date:"P" }}
		  		  	<p style="color:{{ speech.speech.topic.color}}">
				{{ speech.speech.speech_type.name }}
				</p>
		  </div>
		  <div class="col-md-5">

			<a href="{% url 'detail_charla' speech.speech.pk %}" target="_blank"> {{ speech.speech.title }} </a>
		  </div>
		  <div class="col-md-2">{{ speech.speech.user.get_full_name }}</div>
		  <div class="col-md-1">{{ speech.room.name }}</div>
		  <div class="col-md-2">  {% get_registro speech as nreg%}  <a href="{{nreg.url}}"> {{nreg.message}} </a> </div>
		  </div>
			{% endfor %}
			
		{% else %}
		<div class="col-md-2 text-center"> {{ obj.start_time | date:"P" }} a {{ obj.end_time | date:"P" }} </div>
		<div class="col-md-10 text-center"> {{obj.text}}</div>
		
		{% endif %}
		</div>	
	{% endfor %}

<br><br>
{% endblock %}

src/proposal/templates/proposal/speech_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load registro_charla %}
{% block content %}

<h2 style="color: {{object.topic.color}}"> {{ object.title }}<br>
<small> {{ object.topic.name }} </small>
</h2>

<div class="panel panel-success">
  <div class="panel-heading">
  <div class="row">
  <div class="col-md-6">{{object.speech_type}}</div>
  <div class="col-md-4">
  
  {{ schedule.start_time | date:"SHORT_DATE_FORMAT"  }} -- {{ schedule.start_time | date:"P" }} a {{ schedule.end_time | date:"P" }}
  </div>
  <div class="col-md-2">
  {% get_registro schedule as nreg%}  <a class="btn btn-info" href="{{nreg.url}}"> {{nreg.message}} </a>

  </div>
</div>
  
    
  </div>

  <div class="panel-body">
  
    {{ object.description }}
    {% if object.audience and object.audience != " " %}
    	<h2 > Audiencia </h2>
    	{{ object.audience }}
    {% endif %}
  </div>
  <div class="panel-footer">
  <b>Nivel</b>: {{object.get_skill_level_display}} <br>
  {% if object.presentation %}
  <a href="{{object.presentation.url" class="btn btn-warning"> Descargar presentación </a> 
  {% endif %}
  </div>
</div>

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Información (los/las) expositor(es/as)</h3>
  </div>
  <div class="panel-body">
    {{object.speaker_information }}
  </div>
</div>

{% if object.notes and object.notes != " " %}
<div class="alert alert-info">
	{{object.notes}}
</div>
{% endif %}

{% endblock %}

src/proposal/templates/proposal/speech_form.html
{% extends 'base.html' %}

{% load bootstrap  i18n %}

{% block content %}
<div class="row">
	<div class="col-md-6 col-md-offset-4">
<h1 align="center">Propuesta para charlas en el encuentro</h1>
    <form method="post">{% csrf_token %}
    {{ speech_form|bootstrap  }}
    <input class="btn btn-info" type="submit" value="{% trans 'Save' %}">
</form>
</div></div>
<br> <br>
{% endblock %}

src/proposal/templates/proposal/speech_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    {% if period %}
        <a class="btn btn-info"
           href="{% url 'proposal:create' %}">

            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> {% trans 'Add' %} </a>

    {% endif %}
    <br> <br>
    <ul class="list-group">
        {% for object in object_list %}
            <li class="row list-group-item">
                <div class="col-md-9"> {{ object }}</div>
                <form action="{% url 'proposal:delete' object.pk %}" method="POST">
                    {% csrf_token %}
                    <div class="col-md-3">
                        <a class="btn btn-info"
                           href="{% url 'proposal:update' object.pk %}">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> {% trans 'Edit' %}</a>

                        <button class="btn btn-danger">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> {% trans 'Delete' %}
                        </button>
                    </div>
                </form>
            </li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="...">
            <ul class="pager">
                {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
                    </li>
                {% endif %}

                <li>
                    {% trans 'Page' %} {{ page_obj.number }} -- {{ page_obj.paginator.num_pages }}.
                </li>

                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

    {% endif %}

{% endblock %}