src/ECSL/urls.py
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings

from ajax_select import urls as ajax_select_urls
from django.urls import include, path, re_path



urlpatterns = [
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^ajax_select/', include(ajax_select_urls)),
    re_path(r'^accounts/', include('django_registration.backends.activation.urls')),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^paypal/', include('paypal.standard.ipn.urls')),
    re_path(r'', include('ecsl.urls')),
    re_path(r'^proposal/', include('proposal.urls')),
    path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #+ views.becas


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/ecsl/urls.py
from django.urls import path

from ecsl import Profile
from ecsl import becas
from ecsl import charlas as speechviews
from ecsl import contact
from ecsl import payment
from ecsl import views
from ecsl.webservice import get_calendar_json

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('api/agenda.json', get_calendar_json, name="api_json"),
    path('agenda', speechviews.Charlas.as_view(), name="list_charlas"),
    path('edit-agenda', speechviews.EditCharlas.as_view(), name="edit_charlas"),
    path('miagenda', speechviews.MyAgenda.as_view(), name="mi_agenda"),

    path('charla/<int:pk>', speechviews.CharlaDetail.as_view(), name="detail_charla"),
    path('charla/registro/<int:pk>',
         speechviews.register_user_to_speech, name="registra_charla"),
    path('charla/desregistrar/<int:pk>',
         speechviews.desregistrar_charla, name="desregistrar_charla"),
    path('accounts/profile/', Profile.profile_view, name="profile"),
    path('register/profile/create',
         Profile.CreateProfile.as_view(), name='create_profile'),
    path('register/profile/update/<int:pk>', Profile.UpdateProfile.as_view(),
         name='edit_profile'),
    path('registro', payment.payment_view, name='payment'),
    path('registro/create', Profile.CreateRegister.as_view(), name='create_payment'),
    path('registro/update/<int:pk>', payment.PaymentUpdate.as_view(),
         name='edit_payment'),

    path('process-payment/<str:text>', payment.process_payment, name='process_payment'),
    path('payment-done/', payment.payment_done, name='payment_done'),
    path('payment-cancelled/', payment.payment_canceled, name='payment_cancelled'),
    path('sineventos/', views.noEvents, name='no-events'),
    path('becas/', becas.BecasCreate.as_view(), name="becas-create"),
    path('becas/detail/<int:pk>', becas.BecasDetail.as_view(), name="becas-detail"),
    path('contact/', contact.contactUs, name='contact-us'),
    path('contact/send/', contact.contact, name='contact'),
    path('participantes.js', views.get_participants, name="participantes"),
]

src/proposal/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from ecsl.managers import CurrentEventManager
from ecsl.models import EventECSL


class Topic(models.Model):
    name = models.CharField(max_length=150, verbose_name=_("Name"))
    color = models.CharField(max_length=10, default="#fff")
    event = models.ForeignKey(EventECSL, on_delete=models.CASCADE, null=True, blank=False, verbose_name=_("Event"))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Temática"
        verbose_name_plural = "Temáticas"


class SpeechType(models.Model):
    name = models.CharField(max_length=150, verbose_name=_("Name"))
    time = models.IntegerField(default=10, verbose_name=_("Duration (in minutes)"))
    event = models.ForeignKey(EventECSL, null=True, default=None, on_delete=models.CASCADE, verbose_name=_("Event"))
    is_special = models.BooleanField(default=False, verbose_name=_('Is Special Activity'))
    objects = CurrentEventManager()

    def __str__(self):
        return _("%s (%d minutes)") % (self.name, self.time)

    class Meta:
        verbose_name = "Tipo de actividad"
        verbose_name_plural = "Tipos de actividad"


class Speech(models.Model):
    class SKILL_LEVEL:
        EVERYONE = 1
        NOVICE = 2
        INTERMEDIATE = 3
        ADVANCED = 4

        choices = [
            (EVERYONE, _('everyone')),
            (NOVICE, _('novice')),
            (INTERMEDIATE, _('intermediate')),
            (ADVANCED, _('advanced')),
        ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Usuario'))
    speaker_information = models.TextField(
        verbose_name=_("Speaker_information"))
    title = models.TextField(verbose_name=_("Speech Title"))
    description = models.TextField(verbose_name=_("Description"))
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,
                              verbose_name=_("Topic"))
    audience = models.TextField(verbose_name=_("Audience"))
    skill_level = models.PositiveIntegerField(
        choices=SKILL_LEVEL.choices, default=SKILL_LEVEL.EVERYONE,
        verbose_name=_("Skill level required"))
    notes = models.TextField(blank=True,
                             verbose_name=_("Notes for audience"))
    speech_type = models.ForeignKey(SpeechType, on_delete=models.CASCADE, verbose_name=_("Speech Type"))

    presentacion = models.FileField(upload_to='presentaciones/',
                                    verbose_name=_("Presentation"),
                                    null=True, blank=True)
    event = models.ForeignKey(EventECSL, null=True, blank=False, on_delete=models.CASCADE, verbose_name=_("Event"))
    is_scheduled = models.BooleanField(default=False, verbose_name=_('is Scheduled'))

    objects = CurrentEventManager()

    @property
    def speaker_name(self):
        return self.user.get_full_name()

    @property
    def speaker_registered(self):
        dev = False
        try:
            dev = self.user.payment.confirmado
        except:
            pass
        return dev

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('pk',)
        # permissions = (
        #     ("view_speech", "Can see available Speech"),
        # )

        verbose_name = "Actividad"
        verbose_name_plural = "Actividades"


class Room(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Nombre'))
    spaces = models.SmallIntegerField(default=30, verbose_name=_('Spaces'))
    map = models.ImageField(upload_to="mapa", null=True, blank=True, verbose_name=_('Map'))
    event = models.ForeignKey(EventECSL, on_delete=models.CASCADE, verbose_name=_("Event"), null=True, default=None)
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Sala"
        verbose_name_plural = "Salas"


class Register_Speech(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    speech = models.ForeignKey('SpeechSchedule', on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.user.get_full_name(), self.speech.speech.title)

    class Meta:
        verbose_name = "Registro en actividad"
        verbose_name_plural = "Registros en actividades"


class SpeechSchedule(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    speech = models.ForeignKey(Speech, on_delete=models.CASCADE, null=True, blank=True)
    special = models.ForeignKey('SpecialActivity', on_delete=models.CASCADE, null=True, blank=True)
    room = models.ForeignKey('Room', on_delete=models.CASCADE, null=True, default=None)

    def __str__(self):
        return "(%s %s) %s" % (self.start_time.strftime("%Y-%m-%d %H:%M"),
                                     self.end_time.strftime("%Y-%m-%d %H:%M"),
                                     self.room.name)

    @property
    def title(self):
        return self.room.name + " "+str(self.start_time)+" "+str(self.end_time)

    def registros(self):
        regs = Register_Speech.objects.filter(speech=self).count()
        total = self.room.spaces - regs

        dev = "Lleno"
        if total > 0:
            dev = "Hay %d espacios" % (total,)

        return dev

    class Meta:
        verbose_name = "Horario de actividad"
        verbose_name_plural = "Horarios de actividades"


class SpecialActivity(models.Model):
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    type = models.ForeignKey(SpeechType, null=True, on_delete=models.CASCADE, verbose_name=_("Type"))
    message = models.TextField(null=True, blank=True, verbose_name=_("Message"))
    room = models.ForeignKey('Room', null=True, default=None, blank=True, on_delete=models.CASCADE, verbose_name=_("Room"))
    event = models.ForeignKey(EventECSL, default="", on_delete=models.CASCADE, verbose_name=_("Event"))
    is_scheduled = models.BooleanField(default=False, verbose_name=_('is Scheduled'))
    objects = CurrentEventManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actividad Especial"
        verbose_name_plural = "Actividades Especiales"


class BlockSchedule(models.Model):
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    is_speech = models.BooleanField()
    text = models.TextField(null=True, blank=True)
    color = models.CharField(max_length=10)
    room = models.ForeignKey('Room', null=True, default=None, on_delete=models.CASCADE, verbose_name=_("Room"))

    def __str__(self):
        return "%s %s" % (self.start_time.strftime("%Y-%m-%d %H:%M"),
                          self.end_time.strftime("%Y-%m-%d %H:%M"),)

    def get_speech(self, user=None):
        query = SpeechSchedule.objects.filter(
            start_time=self.start_time,
        )
        if user:
            query = query.filter(register_speech__user=user)

        return query.order_by('start_time')

    class Meta:
        verbose_name = "Bloque de horario"
        verbose_name_plural = "Bloques de horarios"

src/ecsl/views.py
import hashlib
import random
import urllib

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.base import TemplateView
from django.urls.base import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from ecsl.models import Inscription, Payment, Becas, EventECSL, Package, PaymentOption
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib import messages
from ecsl.forms import ProfileForm, PaymentForm, ContactForm
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from captcha.fields import CaptchaField
from django.core.mail import EmailMessage, send_mail
from django.core.mail import send_mail
from django.db.models import Count, Q


def noEvents(request):
    current_event = EventECSL.objects.filter(current=True).first()
    if current_event:
        return redirect('index')
    return render(request, 'no_events.html')


class Index(TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        current_event = EventECSL.objects.filter(current=True).first()
        if not current_event:
            return redirect('no-events')
        return super(Index, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        proposal = None
        current_event = EventECSL.objects.filter(current=True).first()

        context = TemplateView.get_context_data(self, **kwargs)
        if self.request.user.is_authenticated:
            try:
                proposal = self.request.user.speech_set.count()
                if proposal > 0:
                    proposal = True
                else:
                    proposal = False
            except Exception as e:
                pass
            beca = Becas.objects.filter(user=self.request.user, event=current_event).first()
            if beca:
                context['becas_period'] = True
                context['beca'] = reverse_lazy('becas-detail')
            else:
                context['becas_period'] = current_event.is_beca_active
                context['beca'] = reverse_lazy('becas-create')
            if proposal:
                context['speech_url'] = proposal

        context['numparticipantes'] = Payment.objects.filter(event=current_event).count()
        context['genero'] = {
            'masculino': Payment.objects.filter(user__inscription__gender='Masculino', event=current_event).count(),
            'femenino': Payment.objects.filter(user__inscription__gender='Femenino', event=current_event).count(),
            'otro': Payment.objects.filter(user__inscription__gender='Otro', event=current_event).count(),
        }

        parms = {
            'panama': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Panamá')),
            'costarica': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Costa Rica')),
            'nicaragua': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Nicaragua')),
            'elsalvador': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='El Salvador')),
            'guatemala': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Guatemala')),
            'honduras': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Honduras')),
            'belize': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Belize')),
            'otro': Count('user__inscription__nationality', filter=Q(user__inscription__nationality='Otro')),
        }

        context['pais'] = Payment.objects.filter(event=current_event).aggregate(**parms)

        if current_event.checking_period:
            context['period'] = current_event.checking_period
        elif proposal:
            context['period'] = True
        context['event_name'] = str(current_event)
        context['event_logo'] = current_event.logo
        date = _("from %(start)s to %(end)s") % {'start': current_event.start_date.strftime("%B %-d"),
                                                 'end': current_event.end_date.strftime("%B %-d, %Y")}
        context['event_dates'] = date
        context['event_location'] = current_event.location
        context['event_description'] = current_event.description

        return context


def get_participants(request):
    dev = []
    default = "https://ecsl2017.softwarelibre.ca/wp-content/uploads/2017/01/cropped-photo_2017-01-30_20-55-06.jpg".encode(
        'utf-8')
    size = 50
    for payment in Payment.objects.all().order_by('?'):
        email = payment.user.email.lower().encode('utf-8')

        insc = Inscription.objects.filter(user=payment.user).first()
        if insc and insc.aparecer_en_participantes:
            name = payment.user.get_full_name()

            url = "https://www.gravatar.com/avatar/%s?%s" % (hashlib.md5(
                email).hexdigest(), urllib.parse.urlencode({'d': default, 's': str(size)}))

            dev.append({'url': url, 'name': name})

    return JsonResponse(dev, safe=False)

src/ecsl/templates/partial/footer.html
{% load static %}
{% load i18n %}
{% load event_tag %}

<footer class="footer">
    <div class="row">
        <div class="col-sm-4 contact-container">
            <div>
                <ul class="list-inline contact-ul">
                    <li>
                        <a>
                            <i class="fas fa-phone-square contact-container"></i>
                        </a>
                            <label>{% phone %}</label>
                    </li>
                    <li>
                        <a>
                            <i class="fas fa-map-marker-alt"></i>
                        </a>
                            <label>{% location %}</label>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-sm-4 text_footer">
            Encuentro Centroamericano de Software Libre
        </div>
        <div class="col-sm-4">
            <div class="footer-container">

                <ul class="list-inline social-media">
                    <li>
                        <a>
                            <i class="fab fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fa fa-fw fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fab fa-instagram"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    </div>
</footer>

src/ecsl/templates/partial/top_navbar.html
{% load static %}
{% load i18n %}


<nav class="navbar navbar-dark bg-inverse">
    <a class="navbar-brand" href="{% url 'index' %}"><strong>ECSL</strong></a>
    <ul class="nav navbar-nav" style="padding: 0;">

        {% if request.user.is_authenticated and request.user.is_staff %}
<li class="dropdown">
  <a class="dropdown-toggle" type="button" id="admindw" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {% trans 'Admin' %}
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" aria-labelledby="admindw">
    <li><a href="{% url 'admin:ecsl_eventecsl_changelist' %}" target="_blank">{% trans 'Events' %}</a></li>
    <li><a href="{% url 'admin:ecsl_becas_changelist' %}" target="_blank">{% trans 'Becas' %}</a></li>
    {% if perms.proposal.add_blockschedule %}
      <li><a href="{% url 'edit_charlas' %}">{% trans 'Build Agenda' %}</a></li>
    {% endif %}
    <li><a href="{% url 'admin:ecsl_payment_changelist' %}" target="_blank">{% trans 'Payment' %}</a></li>
    <li><a href="{% url 'admin:proposal_speech_changelist' %}" target="_blank">{% trans 'Speech' %}</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="/admin" target="_blank">{% trans 'More options in admin site' %}</a></li>
  </ul>
</li>
        {% endif %}
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'profile' %}">Mis datos</a></li>
            <li><a href="{% url 'payment' %}">Registro</a></li>
            <li><a href="{% url 'mi_agenda' %}"> Mi Agenda</a></li>

        {% else %}
            <li><a href="{% url 'django_registration_register' %}">{% trans 'Register' %} </a></li>
        {% endif %}
        <li><a href="{% url 'list_charlas' %}">Agenda</a></li>
        <li><a href="{% url 'contact-us' %}"> Contáctenos </a></li>

    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">
                {% trans 'User:' %} {{ request.user.get_full_name }}<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                {% if request.user.is_authenticated %}

                    <li><a href="{% url 'profile' %}"> {% trans 'Profile' %} </a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'password_reset' %}">{% trans "Change password" %}</a></li>

                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">{% trans "Log out" %}</a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">{% trans "Log in" %}</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
</nav>